apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoprojlabs/argocd-image-updater
  newTag: latest-annotation-based

resources:
- ./config
- ./deployment
- ./rbac
